apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: metallb-operator-webhook-server-service
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    component: webhook-server
status:
  loadBalancer: {}
